apiVersion: v1
kind: Service
metadata:
  name: hive
  namespace: poc-hive
  labels:
    app: hive
    app.kubernetes.io/name: hive
    app.kubernetes.io/part-of: autopoc
spec:
  selector:
    app: hive
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP
  type: ClusterIP
